`timescale 1ns / 1ps

module function_8x3_encoder_tb;
reg [7:0]a;
wire [2:0]out;
function_encoder_8x3 uut(
.a(a),
.out(out)
 );

initial begin  
        a = 8'b00000001; #10;
        a = 8'b00000010; #10;
        a = 8'b00000100; #10;
        a = 8'b00001000; #10;
        a = 8'b00010000; #10;
        a = 8'b00100000; #10;
        a = 8'b01000000; #10;
        a = 8'b10000000; #10;
        a = 8'b00000000; #10;
        $finish;

 end
endmodule



